### ISSUE TITLE
ASGI application compatibility

### ISSUE THREAD

**Issue by avanov** [oldani/asgi-testClient#3]
Hi!

I wonder if the test client is compatible with uvicorn's [ASGI interface](https://www.uvicorn.org/#the-asgi-interface)? I have an app that implements `async def __call__(self, scope, receive, send):` that I'd like to use this test client for, yet it seems it's not compatible with the current TestClient constructor.

**Comment by oldani** [comment]
Hey there,

I will make an upgrade it's just that I have not implemented ASGI 3 interface.

**Comment by oldani** [comment]
Support fro ASGI v2 and v3 have been added to version 0.3.1
